version: "3"

services:
  webdav:
    image: ${DOCKER_IMAGE}
    environment:
      - WEBDAV_USERNAME=admin
      - WEBDAV_PASSWORD=admin
      - SKIP_PERMISSIONS_FIX=no
    volumes:
      - public:/var/webdav/public
      - data:/var/webdav/data
    ports:
      - 80:80

volumes:
  public:
  data: