name: CI

on:
  push:
  schedule:
    - cron: '0 12 * * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test the docker image
      run: |
        DOCKER_IMAGE=docker-php-webdav:latest \
        ./docker-build.sh