name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test the docker image
      run: |
        docker build . --file Dockerfile --tag ${{ steps.variables.outputs.DOCKER_IMAGE }}
        docker-compose up -f "docker-compose.test.yml" up -d --build
        sleep 5
        echo What happens here