name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test the docker image
      run: |
        docker-compose -f docker-compose.test.yml up --build --exit-code-from tester