name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build, test, and release the docker image
      run: |
        DOCKER_SERVER=${DOCKER_SERVER:-docker.pkg.github.com}
        DOCKER_REPO=${DOCKER_REPO:-docker.pkg.github.com/$GITHUB_REPOSITORY/docker-php-webdav}
        VERSION=${GITHUB_REF#refs/tags/v}
        export DOCKER_IMAGE=$DOCKER_REPO:latest

        docker build . --file Dockerfile --tag $DOCKER_IMAGE
        docker-compose -f docker-compose.test.yml up --build --exit-code-from tester

        echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_ACTOR" --password-stdin $DOCKER_SERVER

        echo "Sourcing dockerPushSemver"
        source <(curl -s https://raw.githubusercontent.com/misterjoshua/docker-push-semver-bash/master/docker_push_semver.sh)

        echo "Running dockerPushSemver with $DOCKER_REPO and $VERSION"
        dockerPushSemver $DOCKER_REPO $VERSION