name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build, test, and release the docker image
      env:
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export DOCKER_REPOSITORY=${DOCKER_REPOSITORY:-wheatstalk/docker-php-webdav}
        export DOCKER_IMAGE=$DOCKER_REPOSITORY:latest
        
        # Build
        ./docker-build.sh
        
        # Push to repository
        VERSION=${GITHUB_REF#refs/tags/v} \
        DOCKER_SERVER=${DOCKER_SERVER:-}
        ./docker-push.sh
        